### ISSUE TITLE
A typo in Home page

### ISSUE THREAD

**Issue by shivakrishna9** [Anwesh43/Anwesh43.github.io#1]
In skills, The tile ECMA script is wrongly typed as EMCA script.

**Comment by Anwesh43** [comment]
Hi thanks for pointing the issue i have closed it

**Comment by Anwesh43** [comment]
Here is the commit which will fix the issue https://github.com/Anwesh43/Anwesh43.github.io/commit/4089c8e9eb211b628c2c86bfed6adca1fc6beb0e
